name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: 'ecpix5'
            args: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Tools
        run: |
          apt-get -qy update
          apt-get -qy install wget build-essential python3 python3-pip libevent-dev libjson-c-dev \
            device-tree-compiler python3-requests python3-pexpect

      - name: Install Toolchain
        run: |
          apt-get install gcc-riscv64-linux-gnu g++-riscv64-linux-gnu

      - name: Install Migen / LiteX
        run: |
          wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
          python3 litex_setup.py init install

      - name: Build SoC
        run: |
          export PATH=$PATH:~/.local/bin
          export PATH=$PATH:$(realpath ../riscv64-*/bin)
          git clean -dfx
          ./make.py --board=${{ matrix.board }} ${{ matrix.args }}
          git status

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.board }}
          path: build/*/gateware
